name: pyciam
channels:
  - conda-forge
dependencies:
  - bottleneck=1.3
  - bokeh=2.4.3  # for use of dask dashboard
  - cartopy=0.21.1
  - cloudpathlib=0.13
  - distributed=2023.3.1
  - flox=0.6.8
  - fsspec=2023.3.0
  - geopandas=0.12.2
  - gitpython=3.1.31  # unmarked dependency of rhg_compute_tools
  - jupyterlab=3.6.1
  - matplotlib=3.7.1
  - numpy=1.24.2
  - numpy_groupies=0.9.20
  - oct2py=5.6.0
  - octave=7.3.0
  - openpyxl=3.1.1
  - pandas=1.5.3
  - papermill=2.3.4
  - pint-xarray=0.3
  - pip=23.0.1
  - python=3.11.0
  - requests=2.28.2
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - tqdm=4.65.0
  - xarray=2023.2.0
  - zarr=2.14.2
  - pip:
    - python-ciam==1.1
    - rhg_compute_tools==1.3
    - parameterize_jobs==0.1